name = "NextJS"
match_dependencies = ["next"]
info = "Please make sure you are using output: 'standalone' in your next.config.js"

[build]
image = "node:lts-alpine3.17"
script = """
corepack pnpm install
corepack pnpm run build

cp -r ./public ./.next/standalone/public
"""
artifact = ".next/"

[run]
image = "node:lts-alpine3.17"
script = """
# Setup NextJS standalone (+ static files) environment

ln -s /runner/.next/static /runner/.next/standalone/.next/static
cd .next/standalone

export NODE_ENV=production

node server.js
"""
port = "3000/tcp"
